name: 'build-test'
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - run: npm install
      # Pull this image so it will already be there for unit tests later.
      - run: docker pull ubuntu:22.10
      - run: npm run all
      - name: Run a docker container
        run: docker run --name=test-container ubuntu:22.10 echo "This is a test"
      - name: test
        uses: ./
      - name: Semantic-release
        if: github.ref == 'refs/heads/master'
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
